print('the {} {} {}'.format('fox','brown','quick'))
print('the {2} {1} {0}'.format('fox','brown','quick'))
print('the {f} {b} {q}'.format(f='fox',b='brown',q='quick'))
result=100/777
print(result)
print('bibhu')
print("the result was {r:1.3f}".format(r=result))
print("the result was {r:1.5f}".format(r=result))
print("the result was {r:10.3f}".format(r=result))
print('A %s saved is a %s earned.' %('penny','penny'))
print('A {p} saved is a {p} earned.'.format(p='penny'))
print('{0:8} | {1:9}'.format('Fruit','Quantity'))
print('{0:8} | {1:9}'.format('Apple',3.))
print('{0:8} | {1:9}'.format('Orange',10))
print()
print('{0:<8} | {1:^8} | {2:>8}'.format('left','center','right'))
print('{0:<8} | {1:^8} | {2:>8}'.format(11,22,33))
